"""Adapter TOML schema and loader for memory/system/adapter.toml configuration."""

from __future__ import annotations

import warnings as _warnings
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable

try:
    import tomllib
except ModuleNotFoundError:
    import tomli as tomllib

from memory_core.constants import (
    CURRENT_MEMORY_VERSION,
    SUPPORTED_HOSTS,
    SYNC_DEFAULT_CI_RUNNER,
    SYNC_DEFAULT_SOURCE_REMOTE,
    VALID_SYNC_CI_RUNNERS,
)

# ── migration transforms ──────────────────────────────────────────

def _noop_transform(data: dict[str, Any]) -> dict[str, Any]:
    """Identity transform: returns data unchanged."""
    return data


def _migrate_v010_to_v020(data: dict[str, Any]) -> dict[str, Any]:
    """Transform adapter.toml data from version 0.1.0 to 0.2.0.

    Preserves all existing fields, updates version to CURRENT_MEMORY_VERSION,
    and ensures canonical [core]/[policy]/[routing] layout.
    """
    # If already using canonical layout, just update version
    if "core" in data or "routing" in data:
        result = dict(data)
        if "core" in result:
            result["core"]["version"] = CURRENT_MEMORY_VERSION
        return result

    # Legacy [adapter] section → canonical layout
    adapter = data.get("adapter", {})
    result: dict[str, Any] = {
        "core": {
            "version": CURRENT_MEMORY_VERSION,
            "adapter": adapter.get("adapter", "default"),
        },
        "policy": {},
        "routing": {},
    }

    # Preserve known routing fields
    for key in ("project_name", "project_scope", "host", "canonical_files", "artifact_root"):
        if key in adapter:
            result["routing"][key] = adapter[key]

    # Preserve known policy fields
    for key in ("legality_source_policy", "registration_commit_policy", "registration_commit_phase"):
        if key in adapter:
            result["policy"][key] = adapter[key]

    return result


_MIGRATION_TRANSFORMS: dict[tuple[str, str], Callable[[dict[str, Any]], dict[str, Any]]] = {
    ("0.1.0", CURRENT_MEMORY_VERSION): _migrate_v010_to_v020,
    ("0.2.0", "0.2.0"): _noop_transform,
    (CURRENT_MEMORY_VERSION, CURRENT_MEMORY_VERSION): _noop_transform,
}


def _apply_migration_transforms(
    data: dict[str, Any],
    from_version: str,
    to_version: str,
) -> dict[str, Any]:
    """Apply a registered migration transform to adapter.toml data.

    Raises ``ValueError`` if the version pair is not in the transform registry.
    """
    key = (from_version, to_version)
    transform_fn = _MIGRATION_TRANSFORMS.get(key)
    if transform_fn is None:
        raise ValueError(
            f"No migration transform registered for adapter.toml "
            f"version pair ({from_version!r} -> {to_version!r}). "
            f"Available transforms: {list(_MIGRATION_TRANSFORMS.keys())}"
        )
    return transform_fn(data)


@dataclass
class AdapterConfig:
    """Configuration loaded from ``memory/system/adapter.toml``.

    The canonical TOML layout uses ``[core]``, ``[policy]``, ``[routing]``,
    and optionally ``[global_kb]`` sections.  The legacy single-section
    ``[adapter]`` layout is still accepted for backward compatibility.
    """

    project_name: str
    project_scope: str
    host: str = "factory"
    adapter_version: str = CURRENT_MEMORY_VERSION
    canonical_files: list[str] = field(default_factory=list)
    artifact_root: str | None = None
    # Extra fields preserved from [policy] section
    legality_source_policy: str = "map-only"
    registration_commit_policy: str = "same-commit"
    registration_commit_phase: str = "post"
    # [global_kb] section (v0.8.0+): global knowledge base configuration
    # Default: enabled=True, root=~/.memory/global-kb (expanded)
    global_kb_enabled: bool = True
    global_kb_root: str = str(Path("~/.memory/global-kb").expanduser())


@dataclass
class SyncConfig:
    """Configuration for source-to-mirror sync (adapter.toml [sync] section).

    Optional: when absent or ``enabled=False``, no sync-related files
    are generated by ``memory-init``.  All remote operations (project
    creation, CI variable setup) are handled by Factory hooks, not
    by memory-core.
    """

    enabled: bool = False
    source_remote: str = SYNC_DEFAULT_SOURCE_REMOTE
    mirror_remote: str = ""
    mirror_url: str = ""
    ci_runner: str = SYNC_DEFAULT_CI_RUNNER


# ── known-key whitelists ──────────────────────────────────────────

_KNOWN_CORE_KEYS: frozenset[str] = frozenset({"version", "adapter"})
_KNOWN_POLICY_KEYS: frozenset[str] = frozenset({
    "legality_source_policy",
    "registration_commit_policy",
    "registration_commit_phase",
})
_KNOWN_ROUTING_KEYS: frozenset[str] = frozenset({
    "project_name",
    "project_scope",
    "host",
    "canonical_files",
    "artifact_root",
})
_KNOWN_SYNC_KEYS: frozenset[str] = frozenset({
    "enabled",
    "source_remote",
    "mirror_remote",
    "mirror_url",
    "ci_runner",
})
_KNOWN_GLOBAL_KB_KEYS: frozenset[str] = frozenset({
    "enabled",
    "root",
})


# ── internal helpers ──────────────────────────────────────────────


def _check_unknown_keys(section: str, data: dict[str, Any], known: frozenset[str]) -> None:
    """Raise ``ValueError`` when *data* contains keys outside *known*."""
    for key in data:
        if key not in known:
            raise ValueError(f"unknown key in [{section}]: {key}")


def _toml_str(value: str) -> str:
    """Format a plain string as a TOML basic string."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _has_new_sections(data: dict[str, Any]) -> bool:
    """Return True if *data* uses the [core]/[routing] layout."""
    return "core" in data or "routing" in data


# ── public API ────────────────────────────────────────────────────


def load_adapter_toml(path: Path, *, strict: bool = False) -> AdapterConfig:
    """Load an :class:`AdapterConfig` from *path*.

    Supports two TOML layouts:

    * **Canonical** — ``[core]``, ``[policy]``, ``[routing]`` sections.
    * **Legacy** — single ``[adapter]`` section (backward compat).

    If *path* does not exist, return a default configuration with
    ``project_name`` and ``project_scope`` set to empty strings.

    When *strict* is ``True``, additional validation is performed:
    - Unknown keys in ``[core]`` / ``[policy]`` / ``[routing]`` raise ``ValueError``.
    - Empty/whitespace ``project_scope`` / ``project_name`` raise ``ValueError``.
    - Host values not in ``SUPPORTED_HOSTS`` raise ``ValueError``.
    """
    if not path.is_file():
        return AdapterConfig(project_name="", project_scope="")

    with open(path, "rb") as fh:
        data: dict[str, Any] = tomllib.load(fh)

    if _has_new_sections(data):
        config = _load_new_format(data, strict=strict)
    else:
        # Legacy [adapter] fallback
        section = data.get("adapter") or {}
        config = AdapterConfig(
            project_name=section.get("project_name", ""),
            project_scope=section.get("project_scope", ""),
            host=section.get("host", "factory"),
            adapter_version=section.get("adapter_version", CURRENT_MEMORY_VERSION),
            canonical_files=list(section.get("canonical_files", [])),
            artifact_root=section.get("artifact_root"),
        )

    # Validate host against SUPPORTED_HOSTS
    if config.host and config.host not in SUPPORTED_HOSTS:
        if strict:
            raise ValueError(f"Unsupported host: {config.host!r}, expected one of {SUPPORTED_HOSTS}")
        import warnings
        warnings.warn(
            f"adapter.toml routing.host='{config.host}' is not in SUPPORTED_HOSTS={SUPPORTED_HOSTS}",
            stacklevel=2,
        )

    # Strict: validate non-empty project_scope and project_name
    if strict:
        if not config.project_scope or not config.project_scope.strip():
            raise ValueError("routing.project_scope must be non-empty")
        if not config.project_name or not config.project_name.strip():
            raise ValueError("routing.project_name must be non-empty")

    return config

def _load_new_format(data: dict[str, Any], *, strict: bool = False) -> AdapterConfig:
    """Parse the canonical ``[core]`` / ``[policy]`` / ``[routing]`` / ``[global_kb]`` layout."""
    core: dict[str, Any] = data.get("core", {})
    policy: dict[str, Any] = data.get("policy", {})
    routing: dict[str, Any] = data.get("routing", {})
    global_kb: dict[str, Any] = data.get("global_kb", {})

    if strict:
        _check_unknown_keys("core", core, _KNOWN_CORE_KEYS)
        _check_unknown_keys("policy", policy, _KNOWN_POLICY_KEYS)
        _check_unknown_keys("routing", routing, _KNOWN_ROUTING_KEYS)
        sync = data.get("sync", {})
        if sync:
            _check_unknown_keys("sync", sync, _KNOWN_SYNC_KEYS)
        if global_kb:
            _check_unknown_keys("global_kb", global_kb, _KNOWN_GLOBAL_KB_KEYS)

    project_scope = routing.get("project_scope", "")
    # F4: Only fall back to project_scope when project_name key is missing,
    # not when it's present but empty (empty is validated upstream in strict mode).
    if "project_name" in routing:
        project_name = routing["project_name"]
    else:
        project_name = project_scope
        if not strict:
            if not project_name or not project_name.strip():
                _warnings.warn(
                    "routing.project_name missing; falling back to project_scope (or empty)",
                    stacklevel=2,
                )
            else:
                _warnings.warn(
                    "routing.project_name missing; falling back to project_scope",
                    stacklevel=2,
                )

    # Parse [global_kb] section with defaults
    global_kb_enabled = global_kb.get("enabled", True)
    global_kb_root = global_kb.get("root", "~/.memory/global-kb")
    # Expand ~ to absolute path
    if isinstance(global_kb_root, str):
        global_kb_root = str(Path(global_kb_root).expanduser())

    return AdapterConfig(
        project_name=project_name,
        project_scope=project_scope,
        host=routing.get("host", "factory"),
        adapter_version=core.get("version", CURRENT_MEMORY_VERSION),
        canonical_files=list(routing.get("canonical_files", [])),
        artifact_root=routing.get("artifact_root"),
        legality_source_policy=policy.get("legality_source_policy", "map-only"),
        registration_commit_policy=policy.get("registration_commit_policy", "same-commit"),
        registration_commit_phase=policy.get("registration_commit_phase", "post"),
        global_kb_enabled=global_kb_enabled,
        global_kb_root=global_kb_root,
    )


def load_sync_config(path: Path, *, strict: bool = False) -> SyncConfig:
    """Load :class:`SyncConfig` from the ``[sync]`` section of adapter.toml.

    Returns ``SyncConfig(enabled=False)`` when the section is absent.
    """
    if not path.is_file():
        return SyncConfig()

    with open(path, "rb") as fh:
        data: dict[str, Any] = tomllib.load(fh)

    sync = data.get("sync")
    if not sync:
        return SyncConfig()

    if strict:
        _check_unknown_keys("sync", sync, _KNOWN_SYNC_KEYS)

    ci_runner = sync.get("ci_runner", SYNC_DEFAULT_CI_RUNNER)
    if ci_runner not in VALID_SYNC_CI_RUNNERS:
        if strict:
            raise ValueError(f"sync.ci_runner={ci_runner!r} not in {VALID_SYNC_CI_RUNNERS}")
        _warnings.warn(f"sync.ci_runner={ci_runner!r} not in {VALID_SYNC_CI_RUNNERS}", stacklevel=2)
        ci_runner = SYNC_DEFAULT_CI_RUNNER

    return SyncConfig(
        enabled=bool(sync.get("enabled", False)),
        source_remote=sync.get("source_remote", SYNC_DEFAULT_SOURCE_REMOTE),
        mirror_remote=sync.get("mirror_remote", ""),
        mirror_url=sync.get("mirror_url", ""),
        ci_runner=ci_runner,
    )


def dump_sync_toml(config: SyncConfig) -> str:
    """Serialize :class:`SyncConfig` to a TOML ``[sync]`` section string."""
    lines = ["", "[sync]"]
    lines.append(f"enabled = {str(config.enabled).lower()}")
    lines.append(f"source_remote = {_toml_str(config.source_remote)}")
    if config.mirror_remote:
        lines.append(f"mirror_remote = {_toml_str(config.mirror_remote)}")
    if config.mirror_url:
        lines.append(f"mirror_url = {_toml_str(config.mirror_url)}")
    lines.append(f"ci_runner = {_toml_str(config.ci_runner)}")
    return "\n".join(lines) + "\n"


def dump_adapter_toml(config: AdapterConfig) -> str:
    """Serialize *config* to a TOML string using the canonical layout."""
    lines: list[str] = []

    # [core]
    lines.append("# Memory Adapter Configuration")
    lines.append("")
    lines.append("[core]")
    lines.append(f'version = {_toml_str(config.adapter_version)}')
    lines.append(f'adapter = {_toml_str("default")}')

    # [policy]
    lines.append("")
    lines.append("[policy]")
    lines.append(f'legality_source_policy = {_toml_str(config.legality_source_policy)}')
    lines.append(f'registration_commit_policy = {_toml_str(config.registration_commit_policy)}')
    lines.append(f'registration_commit_phase = {_toml_str(config.registration_commit_phase)}')

    # [routing]
    lines.append("")
    lines.append("[routing]")
    lines.append(f'project_name = {_toml_str(config.project_name)}')
    lines.append(f'project_scope = {_toml_str(config.project_scope)}')
    lines.append(f'host = {_toml_str(config.host)}')

    # canonical_files
    lines.append("canonical_files = [")
    for f in config.canonical_files:
        lines.append(f"  {_toml_str(f)},")
    lines.append("]")

    # artifact_root (optional)
    if config.artifact_root is not None:
        lines.append(f'artifact_root = {_toml_str(config.artifact_root)}')
    else:
        lines.append("# artifact_root is not set")

    # [global_kb] section (v0.8.0+)
    lines.append("")
    lines.append("[global_kb]")
    lines.append(f"enabled = {str(config.global_kb_enabled).lower()}")
    lines.append(f"root = {_toml_str(config.global_kb_root)}")

    return "\n".join(lines) + "\n"

