#!/usr/bin/env python3
"""Safe migrator for applying residue cleanup plans with backup/rollback support.

Usage:
    memory-apply-residue-plan --target /path/to/project --plan plan.json
    memory-apply-residue-plan --target /path/to/project --plan plan.json --dry-run
    memory-apply-residue-plan --target /path/to/project --rollback manifest.json

This tool safely applies migration plans generated by memory-plan-residue.
It implements strict safety rules and requires explicit backups before any
modifications.

Safety guarantees:
    - No plan = rejection (must have valid plan.json)
    - Dry-run mode makes no changes
    - Non-dry-run requires backup manifest creation
    - Human-confirmation plans rejected by default
    - Manual-decision actions rejected by default
    - Forbidden overwrites blocked (AGENTS.md, INDEX.md, project-map/**, CLAUDE.md)
    - Only low-risk auto actions allowed: move_root_pollution, ignore_runtime_artifact
"""
from __future__ import annotations

import argparse
import hashlib
import json
import logging
import shutil
import sys
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from memory_core.ownership import (
    Owned,
    classify_owned_path,
    load_memory_ownership,
)

# Setup logging
logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Step 2.9: FORBIDDEN_OVERWRITE_PATTERNS replaced with classify_owned_path()
# Legacy patterns kept for reference during transition
LEGACY_FORBIDDEN_OVERWRITE_PATTERNS = [
    "AGENTS.md",
    "INDEX.md",
    "project-map/**",
    "CLAUDE.md",
]

# Forbidden files/patterns that must never be overwritten
# Now dynamically populated via classify_owned_path()
FORBIDDEN_OVERWRITE_PATTERNS = []  # type: list[str]

# Allowed low-risk auto actions
ALLOWED_AUTO_ACTIONS = {
    "move_root_pollution",
    "ignore_runtime_artifact",
}

# Default reports destination for move_root_pollution
DEFAULT_REPORTS_DEST = "memory/artifacts/reports"


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------

@dataclass
class ApplyResult:
    """Result of applying a migration plan."""

    success: bool
    target: str
    dry_run: bool
    actions_applied: list[dict[str, Any]] = field(default_factory=list)
    actions_skipped: list[dict[str, Any]] = field(default_factory=list)
    actions_failed: list[dict[str, Any]] = field(default_factory=list)
    backup_manifest: dict[str, Any] | None = None
    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "success": self.success,
            "target": self.target,
            "dry_run": self.dry_run,
            "actions_applied": self.actions_applied,
            "actions_skipped": self.actions_skipped,
            "actions_failed": self.actions_failed,
            "backup_manifest": self.backup_manifest,
            "errors": self.errors,
            "warnings": self.warnings,
            "summary": {
                "applied": len(self.actions_applied),
                "skipped": len(self.actions_skipped),
                "failed": len(self.actions_failed),
                "total": len(self.actions_applied) + len(self.actions_skipped) + len(self.actions_failed),
            },
        }


@dataclass
class BackupEntry:
    """Single backup entry for a file."""

    action: str
    src: str
    dst: str | None
    backup_path: str
    sha256: str
    timestamp: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "action": self.action,
            "src": self.src,
            "dst": self.dst,
            "backup_path": self.backup_path,
            "sha256": self.sha256,
            "timestamp": self.timestamp,
        }


@dataclass
class BackupManifest:
    """Complete backup manifest."""

    version: str
    created_at: str
    target: str
    plan_path: str | None
    entries: list[BackupEntry]

    def to_dict(self) -> dict[str, Any]:
        return {
            "version": self.version,
            "created_at": self.created_at,
            "target": self.target,
            "plan_path": self.plan_path,
            "entries": [e.to_dict() for e in self.entries],
        }


# ---------------------------------------------------------------------------
# Utility functions
# ---------------------------------------------------------------------------

def _sha256_file(path: Path) -> str:
    """Calculate SHA256 hash of a file."""
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def _is_forbidden_path(path: str, target: Path | None = None) -> bool:
    """Step 2.9: Check if a path is forbidden using classify_owned_path.

    Args:
        path: Relative path to check
        target: Project root (optional, for ownership lookup)

    Returns:
        True if path is owned/protected
    """
    # Use classify_owned_path if target is available
    if target is not None:
        try:
            ownership = load_memory_ownership(target)
            classification = classify_owned_path(path, ownership=ownership)
            return isinstance(classification, Owned)
        except Exception:
            pass  # Fall through to legacy check

    # Legacy fallback
    path_lower = path.lower()
    forbidden = ["agents.md", "index.md", "claude.md"]
    if any(f in path_lower for f in forbidden):
        return True
    if "project-map" in path_lower:
        return True
    return False


def _matches_pattern(path: str, pattern: str) -> bool:
    """Simple pattern matching for forbidden paths."""
    import fnmatch
    return fnmatch.fnmatch(path, pattern) or fnmatch.fnmatch(path.lower(), pattern.lower())


def _now_iso() -> str:
    """Current ISO timestamp."""
    return datetime.now(timezone.utc).isoformat()


# ---------------------------------------------------------------------------
# Validation functions
# ---------------------------------------------------------------------------

def _validate_plan(plan: dict[str, Any], target: Path | None = None) -> tuple[bool, list[str]]:
    """Validate migration plan structure.

    Args:
        plan: Plan dictionary to validate
        target: Project root path (optional, for ownership checks)

    Returns (is_valid, error_messages).
    """
    errors: list[str] = []

    if not isinstance(plan, dict):
        errors.append("Plan must be a JSON object")
        return False, errors

    # Check required fields
    required_fields = ["target", "actions", "risk_level", "requires_human_confirmation"]
    for required_field in required_fields:
        if required_field not in plan:
            errors.append(f"Missing required field: {required_field}")

    # Check requires_human_confirmation
    if plan.get("requires_human_confirmation") is True:
        errors.append("Plan requires human confirmation (requires_human_confirmation=true)")

    # Step 2.9: Initialize forbidden patterns from classify_owned_path if target available
    forbidden_paths: set[str] = set()
    if target is not None:
        try:
            ownership = load_memory_ownership(target)
            # Check all files under target
            if target.exists():
                for item in target.rglob("*"):
                    if item.is_file():
                        try:
                            rel_path = item.relative_to(target).as_posix()
                            classification = classify_owned_path(rel_path, ownership=ownership)
                            if isinstance(classification, Owned):
                                forbidden_paths.add(rel_path.lower())
                        except (ValueError, OSError):
                            pass
        except Exception:
            pass  # Fall back to legacy patterns

    # Check actions
    actions = plan.get("actions", [])
    if not isinstance(actions, list):
        errors.append("actions must be a list")
        return False, errors

    for i, action in enumerate(actions):
        if not isinstance(action, dict):
            errors.append(f"Action {i} must be an object")
            continue

        action_type = action.get("action", "")

        # Reject manual_decision_required actions
        if action_type == "manual_decision_required":
            errors.append(f"Action {i} requires manual decision: {action.get('path', 'unknown')}")

        # Step 2.9: Check forbidden overwrites using classify_owned_path
        path = action.get("path", "")
        if path:
            # Check against dynamically loaded owned paths
            if path.lower() in forbidden_paths:
                errors.append(f"Action {i} targets owned/forbidden path: {path}")
            # Also use _is_forbidden_path as fallback
            elif _is_forbidden_path(path, target=target):
                errors.append(f"Action {i} targets forbidden path: {path}")

    return len(errors) == 0, errors


# ---------------------------------------------------------------------------
# Backup functions
# ---------------------------------------------------------------------------

def _create_backup(
    target: Path,
    plan_path: Path | None,
    actions: list[dict[str, Any]],
    backup_dir: Path,
) -> BackupManifest:
    """Create backup for files that will be modified.

    Only backs up files for move_root_pollution actions.
    """
    entries: list[BackupEntry] = []
    timestamp = _now_iso()

    for action in actions:
        action_type = action.get("action", "")

        # Only backup for move_root_pollution
        if action_type != "move_root_pollution":
            continue

        src_path = target / action.get("path", "")
        if not src_path.exists():
            continue

        # Calculate checksum
        sha256 = _sha256_file(src_path)

        # Create backup file
        backup_file = backup_dir / f"{src_path.name}.backup"
        backup_file.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src_path, backup_file)

        entry = BackupEntry(
            action=action_type,
            src=str(src_path.relative_to(target)),
            dst=action.get("target_bucket"),  # This is the conceptual bucket, actual dst calculated later
            backup_path=str(backup_file.relative_to(backup_dir)),
            sha256=sha256,
            timestamp=timestamp,
        )
        entries.append(entry)

    return BackupManifest(
        version="backup-manifest-v1",
        created_at=timestamp,
        target=str(target.resolve()),
        plan_path=str(plan_path) if plan_path else None,
        entries=entries,
    )


def _write_manifest(manifest: BackupManifest, backup_dir: Path) -> Path:
    """Write backup manifest to disk."""
    manifest_path = backup_dir / "manifest.json"
    manifest_path.write_text(
        json.dumps(manifest.to_dict(), indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    return manifest_path


# ---------------------------------------------------------------------------
# Apply functions
# ---------------------------------------------------------------------------

def _apply_move_root_pollution(
    target: Path,
    action: dict[str, Any],
    dry_run: bool,
    reports_dir: Path,
) -> tuple[bool, str, dict[str, Any] | None]:
    """Apply move_root_pollution action.

    Returns (success, message, applied_action_dict).
    """
    src_rel = action.get("path", "")
    src_path = target / src_rel

    if not src_path.exists():
        return True, f"Source file does not exist, skipping: {src_rel}", None

    # Determine destination: artifacts/reports/<original-name>
    dst_rel = f"{DEFAULT_REPORTS_DEST}/{src_path.name}"
    dst_path = target / dst_rel

    # Check if destination already exists
    if dst_path.exists():
        return False, f"Destination already exists, refusing to overwrite: {dst_rel}", None

    if dry_run:
        return (
            True,
            f"Would move: {src_rel} -> {dst_rel}",
            {"action": "move_root_pollution", "src": src_rel, "dst": dst_rel, "status": "dry-run"},
        )

    # Ensure reports directory exists
    reports_dir.mkdir(parents=True, exist_ok=True)

    # Move the file
    try:
        shutil.move(str(src_path), str(dst_path))
        return (
            True,
            f"Moved: {src_rel} -> {dst_rel}",
            {"action": "move_root_pollution", "src": src_rel, "dst": dst_rel, "status": "applied"},
        )
    except Exception as e:
        return False, f"Failed to move {src_rel}: {e}", None


def _apply_ignore_runtime_artifact(
    target: Path,
    action: dict[str, Any],
    dry_run: bool,
) -> tuple[bool, str, dict[str, Any] | None]:
    """Apply ignore_runtime_artifact action.

    Currently only logs that it would be ignored, does not modify .gitignore.
    """
    path = action.get("path", "")

    if dry_run:
        return (
            True,
            f"Would ignore runtime artifact: {path}",
            {"action": "ignore_runtime_artifact", "path": path, "status": "dry-run"},
        )

    # Currently just log, don't modify .gitignore
    return (
        True,
        f"Ignored runtime artifact (no .gitignore modification): {path}",
        {"action": "ignore_runtime_artifact", "path": path, "status": "skipped"},
    )


def _apply_action(
    target: Path,
    action: dict[str, Any],
    dry_run: bool,
    reports_dir: Path,
) -> tuple[bool, str, dict[str, Any] | None]:
    """Apply a single action.

    Returns (success, message, applied_action_dict).
    """
    action_type = action.get("action", "")

    if action_type not in ALLOWED_AUTO_ACTIONS:
        return False, f"Action type not allowed: {action_type}", None

    if action_type == "move_root_pollution":
        return _apply_move_root_pollution(target, action, dry_run, reports_dir)
    elif action_type == "ignore_runtime_artifact":
        return _apply_ignore_runtime_artifact(target, action, dry_run)

    return False, f"Unknown action type: {action_type}", None


# ---------------------------------------------------------------------------
# Rollback functions
# ---------------------------------------------------------------------------

def _load_backup_manifest(manifest_path: Path) -> BackupManifest:
    """Load backup manifest from disk."""
    data = json.loads(manifest_path.read_text(encoding="utf-8"))

    entries = [
        BackupEntry(
            action=e["action"],
            src=e["src"],
            dst=e.get("dst"),
            backup_path=e["backup_path"],
            sha256=e["sha256"],
            timestamp=e["timestamp"],
        )
        for e in data.get("entries", [])
    ]

    return BackupManifest(
        version=data.get("version", "backup-manifest-v1"),
        created_at=data.get("created_at", ""),
        target=data.get("target", ""),
        plan_path=data.get("plan_path"),
        entries=entries,
    )


def _rollback_from_manifest(
    target: Path,
    manifest_path: Path,
    dry_run: bool,
) -> ApplyResult:
    """Rollback changes from a backup manifest."""
    result = ApplyResult(
        success=True,
        target=str(target.resolve()),
        dry_run=dry_run,
    )

    try:
        manifest = _load_backup_manifest(manifest_path)
    except Exception as e:
        result.errors.append(f"Failed to load backup manifest: {e}")
        result.success = False
        return result

    backup_dir = manifest_path.parent

    for entry in manifest.entries:
        if entry.action != "move_root_pollution":
            result.warnings.append(f"Skipping rollback for unsupported action: {entry.action}")
            continue

        src_path = target / entry.src
        backup_full_path = backup_dir / entry.backup_path

        # Check for conflicts
        if src_path.exists():
            result.errors.append(f"Cannot rollback: source already exists (conflict): {entry.src}")
            result.success = False
            continue

        if not backup_full_path.exists():
            result.errors.append(f"Cannot rollback: backup file missing: {entry.backup_path}")
            result.success = False
            continue

        # Verify checksum
        current_sha256 = _sha256_file(backup_full_path)
        if current_sha256 != entry.sha256:
            result.errors.append(f"Cannot rollback: backup checksum mismatch: {entry.backup_path}")
            result.success = False
            continue

        if dry_run:
            result.actions_applied.append({
                "action": "rollback",
                "src": entry.backup_path,
                "dst": entry.src,
                "status": "dry-run",
            })
            continue

        # Perform rollback
        try:
            src_path.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(backup_full_path, src_path)

            # Remove the applied destination if it exists (artifacts/reports/...)
            dst_path = target / f"{DEFAULT_REPORTS_DEST}/{src_path.name}"
            if dst_path.exists():
                dst_path.unlink()

            result.actions_applied.append({
                "action": "rollback",
                "src": entry.backup_path,
                "dst": entry.src,
                "status": "applied",
            })
        except Exception as e:
            result.errors.append(f"Failed to rollback {entry.src}: {e}")
            result.success = False

    return result


# ---------------------------------------------------------------------------
# Main apply logic
# ---------------------------------------------------------------------------

def apply_residue_plan(
    target: Path,
    plan_path: Path | None,
    dry_run: bool,
    backup_dir: Path | None,
    json_output: bool,
) -> ApplyResult:
    """Apply a residue migration plan to a target project.

    Args:
        target: Path to the target project root.
        plan_path: Path to the plan JSON file (None means check stdin or fail).
        dry_run: If True, only report what would be done.
        backup_dir: Directory for backups (default: memory/system/backups/residue-<timestamp>).
        json_output: If True, output results as JSON.

    Returns:
        ApplyResult with success status and details.
    """
    result = ApplyResult(
        success=False,
        target=str(target.resolve()),
        dry_run=dry_run,
    )

    # Validate target
    if not target.exists():
        result.errors.append(f"Target path does not exist: {target}")
        return result

    if not target.is_dir():
        result.errors.append(f"Target path is not a directory: {target}")
        return result

    # Load plan
    if plan_path is None:
        result.errors.append("No plan provided. Use --plan <plan.json> or --rollback <manifest.json>")
        return result

    if not plan_path.exists():
        result.errors.append(f"Plan file does not exist: {plan_path}")
        return result

    try:
        plan_data = json.loads(plan_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        result.errors.append(f"Invalid JSON in plan file: {e}")
        return result
    except Exception as e:
        result.errors.append(f"Failed to read plan file: {e}")
        return result

    # Validate plan (with target for ownership-aware validation)
    is_valid, validation_errors = _validate_plan(plan_data, target=target)
    if not is_valid:
        result.errors.extend(validation_errors)
        return result

    # Determine backup directory
    if backup_dir is None:
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
        backup_dir = target / "memory" / "system" / "backups" / f"residue-{timestamp}"

    # Get actions to apply
    actions = plan_data.get("actions", [])

    # Filter to only allowed actions
    allowed_actions = [a for a in actions if a.get("action", "") in ALLOWED_AUTO_ACTIONS]
    rejected_actions = [a for a in actions if a.get("action", "") not in ALLOWED_AUTO_ACTIONS]

    for action in rejected_actions:
        result.actions_skipped.append({
            "action": action.get("action"),
            "path": action.get("path"),
            "reason": "action type not in allowed list",
        })

    if dry_run:
        # In dry-run, just report what would happen
        for action in allowed_actions:
            action_type = action.get("action", "")
            path = action.get("path", "")

            if action_type == "move_root_pollution":
                src_path = target / path
                if src_path.exists():
                    dst_rel = f"{DEFAULT_REPORTS_DEST}/{src_path.name}"
                    result.actions_applied.append({
                        "action": action_type,
                        "src": path,
                        "dst": dst_rel,
                        "status": "dry-run",
                    })
                else:
                    result.actions_skipped.append({
                        "action": action_type,
                        "path": path,
                        "reason": "source file does not exist",
                    })
            elif action_type == "ignore_runtime_artifact":
                result.actions_applied.append({
                    "action": action_type,
                    "path": path,
                    "status": "dry-run",
                })

        result.success = True
        result.warnings.append("Dry-run mode: no changes made")
        return result

    # Non-dry-run: create backup first
    if not allowed_actions:
        result.warnings.append("No applicable actions to apply")
        result.success = True
        return result

    # Create backup directory
    try:
        backup_dir.mkdir(parents=True, exist_ok=True)
    except Exception as e:
        result.errors.append(f"Failed to create backup directory: {e}")
        return result

    # Create backup
    manifest = _create_backup(target, plan_path, allowed_actions, backup_dir)

    # Apply actions
    reports_dir = target / DEFAULT_REPORTS_DEST

    for action in allowed_actions:
        success, message, applied_dict = _apply_action(target, action, dry_run, reports_dir)

        if applied_dict:
            if success:
                result.actions_applied.append(applied_dict)
            else:
                result.actions_failed.append({**applied_dict, "error": message})
        elif not success:
            result.actions_failed.append({
                "action": action.get("action"),
                "path": action.get("path"),
                "error": message,
            })

    # Update manifest with actual destinations for move operations
    for entry in manifest.entries:
        src_path = target / entry.src
        entry.dst = f"{DEFAULT_REPORTS_DEST}/{src_path.name}"

    # Write manifest
    try:
        manifest_path = _write_manifest(manifest, backup_dir)
        result.backup_manifest = {
            "path": str(manifest_path),
            "entry_count": len(manifest.entries),
        }
    except Exception as e:
        result.errors.append(f"Failed to write backup manifest: {e}")
        result.success = False
        return result

    # Success if no failures
    result.success = len(result.actions_failed) == 0 and len(result.errors) == 0

    return result


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Safe migrator for applying residue cleanup plans with backup/rollback support."
    )
    parser.add_argument(
        "--target",
        type=Path,
        required=True,
        help="Path to the target project root.",
    )
    parser.add_argument(
        "--plan",
        type=Path,
        default=None,
        help="Path to the migration plan JSON file.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Only report what would be done without making changes.",
    )
    parser.add_argument(
        "--backup-dir",
        type=Path,
        default=None,
        help="Directory for backups (default: memory/system/backups/residue-<timestamp>).",
    )
    parser.add_argument(
        "--rollback",
        type=Path,
        default=None,
        help="Path to backup manifest JSON for rollback.",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Output results as JSON.",
    )

    args = parser.parse_args(argv)

    # Validate mutually exclusive options
    if args.plan and args.rollback:
        print("Error: --plan and --rollback are mutually exclusive.", file=sys.stderr)
        return 2

    if args.rollback:
        # Rollback mode
        result = _rollback_from_manifest(args.target, args.rollback, args.dry_run)
    else:
        # Apply mode
        result = apply_residue_plan(
            args.target,
            args.plan,
            args.dry_run,
            args.backup_dir,
            args.json,
        )

    # Output
    if args.json:
        print(json.dumps(result.to_dict(), indent=2, ensure_ascii=False))
    else:
        print("=" * 60)
        print("Residue Plan Application Report")
        print("=" * 60)
        print(f"Target: {result.target}")
        print(f"Mode: {'DRY-RUN' if result.dry_run else 'APPLY'}")
        print("-" * 60)

        if result.backup_manifest:
            print(f"Backup manifest: {result.backup_manifest['path']}")
            print(f"  Entries: {result.backup_manifest['entry_count']}")
            print("-" * 60)

        for action in result.actions_applied:
            status = action.get("status", "applied")
            if action.get("action") == "rollback":
                print(f"  [ROLLBACK] {action.get('src')} -> {action.get('dst')} ({status})")
            elif "dst" in action:
                print(f"  [APPLY] {action.get('src')} -> {action.get('dst')} ({status})")
            else:
                print(f"  [APPLY] {action.get('action')} {action.get('path')} ({status})")

        for action in result.actions_skipped:
            print(f"  [SKIP] {action.get('action')} {action.get('path')}: {action.get('reason')}")

        for action in result.actions_failed:
            print(f"  [FAIL] {action.get('action')} {action.get('path')}: {action.get('error')}")

        for warning in result.warnings:
            print(f"  [WARN] {warning}")

        for error in result.errors:
            print(f"  [ERROR] {error}")

        print("-" * 60)
        summary = result.to_dict()["summary"]
        print(f"Summary: {summary['applied']} applied, {summary['skipped']} skipped, {summary['failed']} failed")
        status = "SUCCESS" if result.success else "FAILED"
        print(f"Status: {status}")
        print("=" * 60)

    return 0 if result.success else 1


if __name__ == "__main__":
    raise SystemExit(main())
