#!/usr/bin/env python3
"""Initialize a .memory/ directory skeleton in a target project.

Usage:
    python init_project_memory.py --target /path/to/project
    python init_project_memory.py --target /path/to/project --dry-run
    python init_project_memory.py --target /path/to/project --dry-run --json
    python init_project_memory.py --target /path/to/project --host claude

This tool creates the minimal .memory/ directory structure required by the
memory system. It is designed to run against a *business project* repository,
NOT against the memory repository itself.

Key guarantees:
    - Default target is the business project repository
    - Does NOT write real project state into the memory repository
    - Generated skeleton passes validate_project_memory.py
"""
from __future__ import annotations

import argparse
import importlib.metadata
import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

CURRENT_MEMORY_VERSION = "0.2.0"

# Claude hook event mapping: (Claude event name -> gateway event flag)
CLAUDE_HOOK_EVENTS: list[tuple[str, str]] = [
    ("SessionStart", "session-start"),
    ("UserPromptSubmit", "prompt-submit"),
    ("Notification", "notification"),
    ("Stop", "stop"),
]

MEMORY_HOOK_BEGIN_MARKER = "<!-- MEMORY_HOOK_BEGIN -->"
MEMORY_HOOK_END_MARKER = "<!-- MEMORY_HOOK_END -->"

# Directory structure to create under .memory/
DIRECTORY_STRUCTURE = [
    ".memory",
    ".memory/kb",
    ".memory/kb/projects",
    ".memory/kb/decisions",
    ".memory/kb/lessons",
    ".memory/kb/global",
]

# ---------------------------------------------------------------------------
# File templates
# ---------------------------------------------------------------------------

def _now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def _slug(text: str) -> str:
    """Normalize a string to a safe project slug: lowercase, hyphens to underscores."""
    return text.lower().replace("-", "_")


def _project_name(target: Path, scope: str | None = None) -> str:
    """Derive a short project name from the target path.

    Priority:
        1. Explicit --scope parameter
        2. git remote origin URL (last segment, stripped of .git)
        3. Target directory name (lowercase)
    """
    if scope:
        return _slug(scope)

    # Try git remote
    try:
        import subprocess
        result = subprocess.run(
            ["git", "-C", str(target), "remote", "get-url", "origin"],
            capture_output=True, text=True, timeout=5,
        )
        if result.returncode == 0 and result.stdout.strip():
            url = result.stdout.strip().rstrip("/")
            # Strip .git suffix
            if url.endswith(".git"):
                url = url[:-4]
            # Extract last path segment (after last / or :)
            segment = url.rsplit("/", 1)[-1].rsplit(":", 1)[-1]
            if segment:
                return _slug(segment)
    except Exception:
        pass

    # Fallback: directory name, lowercase
    return _slug(target.resolve().name)


def template_memory_lock(project_name: str) -> str:
    """Generate memory.lock content."""
    now = _now_iso()
    return json.dumps(
        {
            "version": CURRENT_MEMORY_VERSION,
            "project": project_name,
            "initialized": now,
            "updated": now,
            "schema": "context-package-v1",
            "locked": False,
        },
        indent=2,
        ensure_ascii=False,
    ) + "\n"


def template_adapter_toml(project_name: str) -> str:
    """Generate adapter.toml content conforming to the canonical schema."""
    now = _now_iso()
    return f"""\
# Memory Adapter Configuration
# Auto-generated by init_project_memory.py
# Schema: [core] + [policy] + [routing]

[core]
# Adapter protocol version and type
version = "{CURRENT_MEMORY_VERSION}"
adapter = "default"

[policy]
# How the gateway resolves legal source documents
legality_source_policy = "map-only"
# When registration commits happen relative to absorption
registration_commit_policy = "same-commit"
# Commit phase declaration (post = after context build)
registration_commit_phase = "post"

[routing]
# Project identity — drives scope resolution and canonical lookup
project_name = "{project_name}"
project_scope = "{project_name}"
# Host platform: codex | claude
host = "codex"
"""


def template_canonical_md(project_name: str) -> str:
    """Generate CANONICAL.md with frontmatter."""
    now = _now_iso()
    return f"""\
---
type: "KB:PROJECT"
title: "{project_name} Project Canonical"
shortname: "{project_name}"
status: active
created: "{now}"
updated: "{now}"
scope: project
source: local-canonical
confidence: high
tags: [project, initialized]
---

# {project_name} Project Canonical

## 目标

项目记忆系统已初始化。

## 仓库

| 位置 | 路径 |
|------|------|
| 本地仓库 | `{Path.cwd()}` |

## Truth Basis

### Source Refs
- `workspace/INDEX.md`

### Authority Refs
- `.memory/CANONICAL.md`

### Conflict Status
- `active`
"""


def template_plan_md(project_name: str) -> str:
    """Generate PLAN.md with frontmatter."""
    now = _now_iso()
    return f"""\
---
type: "KB:PLAN"
title: "{project_name} Plan"
shortname: "{project_name}"
status: active
created: "{now}"
---

# {project_name} Plan

## 目标

（待填写）

## 范围

（待填写）
"""


def template_state_md(project_name: str) -> str:
    """Generate STATE.md with frontmatter."""
    now = _now_iso()
    return f"""\
---
type: "KB:STATE"
title: "{project_name} State"
shortname: "{project_name}"
status: active
updated: "{now}"
---

# {project_name} State

> 最后更新：{now}
> 更新者：init_project_memory

## 总体状态：已初始化

## 任务进度

（待填写）
"""


def template_tasks_md(project_name: str) -> str:
    """Generate TASKS.md with frontmatter."""
    now = _now_iso()
    return f"""\
---
type: "KB:TASKS"
title: "{project_name} Tasks"
shortname: "{project_name}"
status: active
---

# {project_name} Tasks

## 任务列表

（待填写）
"""


def template_migrations_log(project_name: str) -> str:
    """Generate initial migrations.log."""
    now = _now_iso()
    return f"""\
# Migrations Log
# Format: TIMESTAMP | VERSION_FROM | VERSION_TO | STATUS | NOTES

{now}T00:00:00Z | none | {CURRENT_MEMORY_VERSION} | applied | initial scaffold
"""


# ---------------------------------------------------------------------------
# File registry
# ---------------------------------------------------------------------------

FILE_TEMPLATES: dict[str, Any] = {
    "memory.lock": lambda pn: template_memory_lock(pn),
    "adapter.toml": lambda pn: template_adapter_toml(pn),
    "CANONICAL.md": lambda pn: template_canonical_md(pn),
    "PLAN.md": lambda pn: template_plan_md(pn),
    "STATE.md": lambda pn: template_state_md(pn),
    "TASKS.md": lambda pn: template_tasks_md(pn),
    "migrations.log": lambda pn: template_migrations_log(pn),
}

# ---------------------------------------------------------------------------
# Keep files
# ---------------------------------------------------------------------------

def template_keep() -> str:
    """Generate a .keep file content."""
    return ""



# ---------------------------------------------------------------------------
# Hooks / AGENTS.md helpers
# ---------------------------------------------------------------------------

def template_hooks_json(host: str = "claude") -> dict[str, Any]:
    """Generate hooks.json content as a dict."""
    hooks: list[dict[str, Any]] = []
    for claude_event, gateway_event in CLAUDE_HOOK_EVENTS:
        hooks.append({
            "event": claude_event,
            "command": f"memory-hook-gateway --host {host} --event {gateway_event}",
            "stdin": True,
        })
    return {"hooks": hooks}


def generate_hooks_json(
    target: Path,
    *,
    host: str = "claude",
    result: dict[str, Any] | None = None,
) -> None:
    """Create or update .claude/hooks.json in the target project.

    If the file already exists, only append missing memory hook entries
    (idempotent — does not overwrite existing hooks from other tools).
    """
    hooks_dir = target / ".claude"
    hooks_path = hooks_dir / "hooks.json"

    if result is None:
        return

    desired = template_hooks_json(host)
    desired_keys = {(h["event"], h["command"]) for h in desired["hooks"]}

    if hooks_path.exists():
        try:
            existing = json.loads(hooks_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            existing = {}

        existing_hooks: list[dict[str, Any]] = existing.get("hooks", [])
        existing_keys = {(h["event"], h["command"]) for h in existing_hooks}
        missing_keys = desired_keys - existing_keys

        if not missing_keys:
            result["skipped"].append("file:.claude/hooks.json (up-to-date)")
            return

        for hook in desired["hooks"]:
            if (hook["event"], hook["command"]) in missing_keys:
                existing_hooks.append(hook)
        existing["hooks"] = existing_hooks
        content = json.dumps(existing, indent=2, ensure_ascii=False) + "\n"
    else:
        hooks_dir.mkdir(parents=True, exist_ok=True)
        content = json.dumps(desired, indent=2, ensure_ascii=False) + "\n"

    hooks_path.write_text(content, encoding="utf-8")
    result["created"].append("file:.claude/hooks.json")


def template_agents_md_block(host: str = "codex") -> str:
    """Generate the AGENTS.md memory hook instruction block."""
    return f"""{MEMORY_HOOK_BEGIN_MARKER}
## Memory Hook

When starting a session, run the memory hook gateway to load project context:

```bash
python -m memory_core.tools.memory_hook_gateway --host {host} --event session-start
```
{MEMORY_HOOK_END_MARKER}
"""


def update_agents_md(
    target: Path,
    *,
    host: str = "codex",
    result: dict[str, Any] | None = None,
) -> None:
    """Insert or update the Memory Hook instruction block in AGENTS.md.

    Idempotent: if the markers already exist, the block content is replaced
    in-place rather than appended.
    """
    if result is None:
        return

    agents_path = target / "AGENTS.md"
    new_block = template_agents_md_block(host)

    if agents_path.exists():
        content = agents_path.read_text(encoding="utf-8")
        has_begin = MEMORY_HOOK_BEGIN_MARKER in content
        has_end = MEMORY_HOOK_END_MARKER in content

        if has_begin and has_end:
            begin_idx = content.index(MEMORY_HOOK_BEGIN_MARKER)
            end_idx = content.index(MEMORY_HOOK_END_MARKER) + len(MEMORY_HOOK_END_MARKER)
            before = content[:begin_idx]
            after = content[end_idx:]

            # Strip trailing newlines from before, prepend a single newline
            before = before.rstrip("\n")
            if before:
                before = before + "\n"

            # Strip leading newlines from after, append a single newline
            after = after.lstrip("\n")
            if after:
                after = "\n" + after

            new_content = before + new_block + after

            if new_content == content:
                result["skipped"].append("file:AGENTS.md (hook block up-to-date)")
                return

            agents_path.write_text(new_content, encoding="utf-8")
            result["created"].append("file:AGENTS.md (hook block updated)")
            return

        new_content = content.rstrip("\n") + "\n\n" + new_block
    else:
        new_content = new_block

    agents_path.write_text(new_content, encoding="utf-8")
    result["created"].append("file:AGENTS.md")


# ---------------------------------------------------------------------------
# Initialization logic
# ---------------------------------------------------------------------------

def init_project_memory(
    target: Path,
    *,
    scope: str | None = None,
    host: str = "codex",
    dry_run: bool = False,
    json_output: bool = False,
) -> dict[str, Any]:
    """Initialize .memory/ directory skeleton in the target project.

    Args:
        target: Path to the target project root.
        scope: Explicit project scope name (auto-discovered if omitted).
        host: Host platform for hook config ("codex" or "claude").
        dry_run: If True, only report what would be created.
        json_output: If True, return structured output dict.

    Returns:
        Dict with 'success', 'created', 'skipped', 'errors' keys.
    """
    result: dict[str, Any] = {
        "success": False,
        "dry_run": dry_run,
        "target": str(target.resolve()),
        "created": [],
        "skipped": [],
        "errors": [],
    }

    memory_root = target / ".memory"
    project_name = _project_name(target, scope)

    if dry_run:
        result["success"] = True
        result["dry_run_output"] = {
            "would_create_dirs": list(DIRECTORY_STRUCTURE),
            "would_create_files": list(FILE_TEMPLATES.keys()),
            "project_name": project_name,
        }
        return result

    # Safety guard: do NOT initialize inside the memory repo itself
    repo_root = _find_repo_root(target)
    if repo_root and _is_memory_repo(repo_root):
        result["errors"].append(
            "Refusing to initialize .memory/ inside the memory repository itself. "
            "This tool is for business project repositories only."
        )
        return result

    # Create directories
    for dir_rel in DIRECTORY_STRUCTURE:
        dir_path = target / dir_rel
        try:
            dir_path.mkdir(parents=True, exist_ok=True)
            result["created"].append(f"dir:{dir_rel}")
        except Exception as exc:
            result["errors"].append(f"failed to create {dir_rel}: {exc}")

    # Create .keep files in empty directories
    for dir_rel in DIRECTORY_STRUCTURE:
        if dir_rel == ".memory":
            continue
        keep_path = target / dir_rel / ".keep"
        if not keep_path.exists():
            try:
                keep_path.write_text("", encoding="utf-8")
                result["created"].append(f"file:{dir_rel}/.keep")
            except Exception as exc:
                result["errors"].append(f"failed to create {dir_rel}/.keep: {exc}")

    # Create template files
    for fname, template_fn in FILE_TEMPLATES.items():
        file_path = memory_root / fname
        if file_path.exists():
            result["skipped"].append(f"file:{fname} (already exists)")
            continue
        try:
            content = template_fn(project_name)
            file_path.write_text(content, encoding="utf-8")
            result["created"].append(f"file:{fname}")
        except Exception as exc:
            result["errors"].append(f"failed to create {fname}: {exc}")

    result["success"] = len(result["errors"]) == 0

    # Generate hooks.json and AGENTS.md after .memory/ is ready
    if result["success"]:
        generate_hooks_json(target, host=host, result=result)
        update_agents_md(target, host=host, result=result)

    return result


def _find_repo_root(path: Path) -> Path | None:
    """Walk up from path to find the git repository root."""
    current = path.resolve()
    while current != current.parent:
        if (current / ".git").is_dir():
            return current
        current = current.parent
    return None


def _is_memory_repo(repo_root: Path) -> bool:
    """Heuristic: is this repo the memory repo?"""
    indicators = [
        repo_root / "workspace" / "tools" / "memory_hook_gateway.py",
        repo_root / "workspace" / "memory",
    ]
    return any(p.is_file() or p.is_dir() for p in indicators)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Initialize a .memory/ directory skeleton in a target project."
    )
    parser.add_argument(
        "--target",
        type=Path,
        required=True,
        help="Path to the target project root (business project repository).",
    )
    parser.add_argument(
        "--scope",
        type=str,
        default=None,
        help="Explicit project scope name. If omitted, auto-discovered from git remote or directory name.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Only report what would be created without writing files.",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Output results as JSON.",
    )
    parser.add_argument(
        "--host",
        type=str,
        default="codex",
        choices=("codex", "claude"),
        help="Host platform for hook gateway configuration (default: codex).",
    )
    try:
        _pkg_version = importlib.metadata.version("memory-core")
    except importlib.metadata.PackageNotFoundError:
        _pkg_version = "unknown"
    parser.add_argument("--version", action="version", version=f"%(prog)s {_pkg_version}")
    args = parser.parse_args()

    target = args.target.resolve()
    if not target.is_dir():
        print(f"Error: target path does not exist or is not a directory: {target}", file=sys.stderr)
        return 2

    result = init_project_memory(
        target,
        scope=args.scope,
        host=args.host,
        dry_run=args.dry_run,
        json_output=args.json,
    )

    if args.json or args.dry_run:
        print(json.dumps(result, indent=2, ensure_ascii=False))
    else:
        print("=" * 60)
        print("Project Memory Initialization Report")
        print("=" * 60)
        if result["dry_run"]:
            print(f"  [DRY RUN] Would initialize .memory/ under: {result['target']}")
            do = result.get("dry_run_output", {})
            print(f"  Project name: {do.get('project_name', 'N/A')}")
            print(f"  Would create {len(do.get('would_create_dirs', []))} directories")
            print(f"  Would create {len(do.get('would_create_files', []))} files")
        else:
            for path in result.get("created", []):
                print(f"  [CREATE] {path}")
            for path in result.get("skipped", []):
                print(f"  [SKIP]   {path}")
            for err in result.get("errors", []):
                print(f"  [ERROR]  {err}")
        print("-" * 60)
        status = "SUCCESS" if result["success"] else "FAILED"
        print(f"  Status: {status}")
        print("=" * 60)

    return 0 if result["success"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
