"""Sync configuration templates for memory-init.

Generates CI pipeline files and documentation blocks based on
:class:`~memory_core.tools.adapter_toml_schema.SyncConfig`.

This module produces **only text** -- no remote API calls, no credential
access, no side effects beyond file writes (handled by the caller).
"""
from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from memory_core.tools.adapter_toml_schema import SyncConfig


def generate_gitlab_ci_yml(sync: SyncConfig, *, project_slug: str = "") -> str:
    """Generate a ``.gitlab-ci.yml`` string for a project with sync enabled.

    Parameters
    ----------
    sync:
        A :class:`SyncConfig` with ``enabled=True``.
    project_slug:
        Optional project identifier for comments.
    """
    mirror_remote = sync.mirror_remote or "github"
    mirror_url = sync.mirror_url or "github.com/example/repo"
    header = "# .gitlab-ci.yml — auto-generated by memory-init"
    if project_slug:
        header += f" for {project_slug}"

    return f"""{header}

stages:
  - test
  - sync

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

cache:
  paths:
    - .pip-cache/

test:
  stage: test
  before_script:
    - python3 -m venv /tmp/ci-venv
    - source /tmp/ci-venv/bin/activate
    - pip install --upgrade pip pytest ruff
  script:
    - source /tmp/ci-venv/bin/activate
    - ruff check .
    - python -m pytest -q tests
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'

# {mirror_remote} is a read-only mirror. All development happens on GitLab.
# Only sync after test passes.
# Never push directly to {mirror_remote} from any machine; only GitLab CI can push.
sync-to-{mirror_remote}:
  stage: sync
  needs: [test]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"'
  before_script:
    - git config --global user.name "ci-sync"
    - git config --global user.email "ci-sync@${{CI_SERVER_HOST}}"
  script:
    - git checkout -B main HEAD
    - git remote remove {mirror_remote} 2>/dev/null || true
    - git remote add {mirror_remote} "https://x-access-token:${{{mirror_remote.upper().replace("-", "_")}_TOKEN}}@{mirror_url}"
    - git commit --amend --reset-author --no-edit
    - git push {mirror_remote} main --force
"""


def generate_agents_md_sync_block(sync: SyncConfig) -> str:
    """Generate the AGENTS.md iron-rule block for sync.

    Returns an empty string when ``sync.enabled`` is ``False``.
    """
    if not sync.enabled:
        return ""

    source = sync.source_remote
    mirror = sync.mirror_remote or "mirror"
    return f"""<!-- SYNC_IRON_RULE_BEGIN -->
## Sync Iron Rule: {source} -> {mirror}

**All Factory/Droid接入的项目必须遵守：**

1. **代码只推 {source}** -- Agent/人/CI 都只 push 到 {source}，创建 MR
2. **CI 门禁** -- test 通过后才可合并到 main
3. **{mirror} 是只读镜像** -- 只有 CI sync-to-{mirror} job 可以推 {mirror}
4. **禁止直推 {mirror}** -- 任何 `git push {mirror} main` 都是违规，会破坏单源真相
5. **违规恢复** -- 如果意外直推 {mirror}，回退 commit，重新走 {source} 流程
<!-- SYNC_IRON_RULE_END -->
"""


def generate_contributing_sync_block(sync: SyncConfig) -> str:
    """Generate the CONTRIBUTING.md sync section.

    Returns an empty string when ``sync.enabled`` is ``False``.
    """
    if not sync.enabled:
        return ""

    source = sync.source_remote
    mirror = sync.mirror_remote or "mirror"
    return f"""### {source} -> {mirror} Sync Rule

| Rule | Description |
|------|-------------|
| Local -> {source} | Push branch + MR, CI gate must pass before merge |
| {source} -> {mirror} | CI sync job only, after test passes |
| No Local -> {mirror} | No machine/agent may directly `git push {mirror}` |

If code is accidentally pushed directly to {mirror}:
1. Revert the {mirror} commit.
2. Re-submit the change through {source} MR flow.
3. Verify CI sync restores consistency.
"""
