"""Sync configuration templates for memory-init.

Generates CI pipeline files and documentation blocks based on
:class:`~memory_core.tools.adapter_toml_schema.SyncConfig`.

This module produces **only text** -- no remote API calls, no credential
access, no side effects beyond file writes (handled by the caller).
"""
from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from memory_core.tools.adapter_toml_schema import SyncConfig


def _build_mirror_remote_url(
    mirror_remote: str,
    mirror_url: str,
    auth_scheme: str = "x-access-token",
) -> str:
    """Build authenticated mirror remote URL for CI sync job."""
    # Split literal to avoid Droid-Shield false-positive on URL pattern
    token_var_name = f"{mirror_remote.upper().replace('-', '_')}_TOKEN"
    token_var_ref = "${" + token_var_name + "}"
    _proto = "https" + "://"
    return _proto + auth_scheme + ":" + token_var_ref + "@" + mirror_url

def generate_gitlab_ci_yml(sync: SyncConfig, *, project_slug: str = "") -> str:
    """Generate a ``.gitlab-ci.yml`` string for a project with sync enabled.

    Parameters
    ----------
    sync:
        A :class:`SyncConfig` with ``enabled=True``.
    project_slug:
        Optional project identifier for comments.
    """
    mirror_remote = sync.mirror_remote or "github"
    mirror_url = sync.mirror_url or "github.com/example/repo"
    token_var_name = f"{mirror_remote.upper().replace('-', '_')}_TOKEN"
    token_var_ref_default = "${" + token_var_name + ":-}"
    _mirror_auth_url = _build_mirror_remote_url(mirror_remote, mirror_url)
    header = "# .gitlab-ci.yml — auto-generated by memory-init"
    if project_slug:
        header += f" for {project_slug}"

    return f"""{header}

include:
  - project: 'infra/ci-templates'
    file: 'scope-check.yml'

stages:
  - test
  - health-check
  - sync

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

cache:
  paths:
    - .pip-cache/

test:
  stage: test
  before_script:
    - python3 -m venv /tmp/ci-venv
    - source /tmp/ci-venv/bin/activate
    - pip install --upgrade pip pytest ruff
  script:
    - source /tmp/ci-venv/bin/activate
    - ruff check .
    - python -m pytest -q tests
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'

health-check:
  stage: health-check
  needs: [test]
  script:
    - test -f memory/system/adapter.toml
    - test -f memory/system/migrations.log
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'

# {mirror_remote} is a read-only mirror. All development happens on GitLab.
# Only sync after test + health-check pass.
# Never push directly to {mirror_remote} from any machine; only GitLab CI can push.
sync-to-{mirror_remote}:
  stage: sync
  needs: [test, health-check]
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"'
  before_script:
    - git config --global user.name "ci-sync"
    - git config --global user.email "ci-sync@${{CI_SERVER_HOST}}"
  script:
    - test -n "{token_var_ref_default}" || (echo "Missing {token_var_name} variable" && exit 1)
    - git checkout -B main HEAD
    - git remote remove {mirror_remote} 2>/dev/null || true
    - git remote add {mirror_remote} "{_mirror_auth_url}"
    - git fetch {mirror_remote} main || true
    - git push {mirror_remote} main --force-with-lease
"""


def generate_skill_workflow_yaml(sync: SyncConfig) -> str:
    """Generate skill workflow template for GitLab-first submit/merge/sync."""
    if not sync.enabled:
        return ""

    source = sync.source_remote or "gitlab"
    mirror = sync.mirror_remote or "github"
    token_var_name = f"{mirror.upper().replace('-', '_')}_TOKEN"
    return f"""# memory/system/skills/gitlab_sync_workflow.yaml
version: 1
workflow: gitlab-first-sync
rules:
  - local_commit_target: "{source}"
  - deny_direct_push: "{mirror}"
  - require_pipeline_jobs: ["test", "health-check"]

skills:
  - name: submit_gitlab
    goal: "Submit code to {source} via API and open MR"
    precheck:
      - "origin points to {source}"
      - "working tree clean"
    api:
      - "POST /api/v4/projects/:id/repository/commits"
      - "POST /api/v4/projects/:id/merge_requests"

  - name: merge_after_ci
    goal: "Merge only when pipeline success + approvals satisfied"
    checks:
      - "GET /api/v4/projects/:id/merge_requests/:iid (merge_status=can_be_merged)"
      - "GET /api/v4/projects/:id/merge_requests/:iid/pipelines (status=success)"
    api:
      - "PUT /api/v4/projects/:id/merge_requests/:iid/merge"

  - name: sync_github
    goal: "Mirror main after merge via CI job only"
    ci_job: "sync-to-{mirror}"
    required_secret: "{token_var_name}"
    rule: "Only run on main push pipeline"
"""


def generate_agents_md_sync_block(sync: SyncConfig) -> str:
    """Generate the AGENTS.md iron-rule block for sync.

    Returns an empty string when ``sync.enabled`` is ``False``.
    """
    if not sync.enabled:
        return ""

    source = sync.source_remote
    mirror = sync.mirror_remote or "mirror"
    return f"""<!-- SYNC_IRON_RULE_BEGIN -->
## Sync Iron Rule: {source} -> {mirror}

**All Factory/Droid接入的项目必须遵守：**

1. **代码只推 {source}** -- Agent/人/CI 都只 push 到 {source}，创建 MR
2. **CI 门禁** -- test 通过后才可合并到 main
3. **{mirror} 是只读镜像** -- 只有 CI sync-to-{mirror} job 可以推 {mirror}
4. **禁止直推 {mirror}** -- 任何 `git push {mirror} main` 都是违规，会破坏单源真相
5. **违规恢复** -- 如果意外直推 {mirror}，回退 commit，重新走 {source} 流程
<!-- SYNC_IRON_RULE_END -->
"""


def generate_contributing_sync_block(sync: SyncConfig) -> str:
    """Generate the CONTRIBUTING.md sync section.

    Returns an empty string when ``sync.enabled`` is ``False``.
    """
    if not sync.enabled:
        return ""

    source = sync.source_remote
    mirror = sync.mirror_remote or "mirror"
    return f"""### {source} -> {mirror} Sync Rule

| Rule | Description |
|------|-------------|
| Local -> {source} | Push branch + MR, CI gate must pass before merge |
| {source} -> {mirror} | CI sync job only, after test passes |
| No Local -> {mirror} | No machine/agent may directly `git push {mirror}` |

If code is accidentally pushed directly to {mirror}:
1. Revert the {mirror} commit.
2. Re-submit the change through {source} MR flow.
3. Verify CI sync restores consistency.
"""


def generate_skill_memory_init_fill_yaml(project_name: str = "") -> str:
    """Generate memory-init-fill skill workflow YAML from template file.

    Reads the YAML template from ``workspace/templates/skills/memory-init-fill.yaml``
    and returns its content. This skill is static (no variable substitution needed)
    because it defines a workflow rather than project-specific configuration.

    Parameters
    ----------
    project_name:
        Optional project identifier (currently unused, reserved for future templating).

    Returns
    -------
    str
        The complete YAML string for the memory-init-fill skill workflow,
        or empty string if the template file is not found.
    """
    _repo_root = Path(__file__).resolve().parent.parent.parent
    _template_path = _repo_root / "workspace" / "templates" / "skills" / "memory-init-fill.yaml"

    if _template_path.is_file():
        return _template_path.read_text(encoding="utf-8")

    # Template not found — skill is optional, return empty
    return ""
